version: '2'

services:
  db:
    image: postgres:9.6
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
  redis:
    image: redis:3.2.4-alpine
    ports:
      - '6379:6379'
  sidekiq: 
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    links:
      - db
      - redis
  app:
    build: .
    depends_on:
      - 'db'
      - 'redis'  
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - '4000:4000'
    links:
      - db
      - redis
    volumes:
      - '.:/app'  

