default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  port: 5432
development:
  <<: *default
  database: reddit_clone_dev

production:
  <<: *default
  database: reddit_clone_prod
  
test:
  <<: *default
  database: reddit_clone_test
